### ISSUE TITLE
Feat: support form @angular/material form field errors 

### ISSUE THREAD

**Issue by badre429** [ng-turkey/ngx-validate#52]
Angular material form field generate div wrapper for the input and the validation error component must be in other div 
there for then selection of  validation component location must be function in config
 
this is as l[ive demo](https://stackblitz.com/edit/ngx-validate-mw8ade?file=src%2Fapp%2Fcomponents%2Fapp.component.html)

**Comment by armanozak** [comment]
Hi @badre429,

Thank you very much for your contribution. The library is still evolving and your point is valid. We will take this as a feature and implement it before v1.

Have a nice day.

**Comment by rqx110** [comment]
also consider other ui framework. eg: [ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

**Comment by mikkelalstrup** [comment]
Hi @armanozak ,
Do you have any update on when this is going to be implemented?
This is relevant for our project atm.

Have a nice day!

**Comment by armanozak** [comment]
Hi @badre429, @rqx110, and @mikkelalstrup,

We have developed a solution for Material and have just published v0.1.0 to npm. Please check the example:

https://stackblitz.com/edit/ngx-validate-1niswy?file=src%2Fapp%2Fcomponents%2Fapp.component.html

We have introduced a new directive called `ValidationContainerDirective` (with `[validationContainer]` selector). Now you can use this new directive to get a `ValidationTargetDirective` which is not a parent of the form control. This should also be working in other UI libraries.

Please try the new feature and let us know if it works as expected.

Have a nice day.

**Comment by badre429** [comment]
@armanozak  thanks for you valuable work this library save as huge amount of time
