### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by Loongle** [ng-turkey/ngx-validate#75]
![image](https://user-images.githubusercontent.com/7290992/139585818-ca303436-447f-49af-9cc0-9f38367cf86c.png)

node version: v14.17.5
npm version: 7.20.6
angular cli version: 12.2.11

**Comment by bnymncoskuner** [comment]
Hello, 

It could be related to your npm version. Could you please try it with npm v6.x or yarn?

**Comment by Loongle** [comment]
Yes, This problem exists in the latest npm version. I think it should be fixed
