### ISSUE TITLE
"Ivy" distribution

### ISSUE THREAD

**Issue by hillin** [ng-turkey/ngx-validate#90]
This is what angular says every time when I build my project:

> Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
> - @ngx-validate/core [es2015/esm2015] (git+https://github.com/ng-turkey/ngx-validate.git)
> Encourage the library authors to publish an Ivy distribution.

Guess someone has to make the encouragement!

**Comment by mahmut-gundogdu** [comment]
@hillin  we will prepare a new release, then it will be fixed. I am working on it.

**Comment by hillin** [comment]
Hey, another year has passed!

**Comment by hillin** [comment]
Apparently the 0.2.0 version has solved this issue.
