### ISSUE TITLE
Ngx-validate should work, when  the ValidationGroupDirective is null.  

### ISSUE THREAD

**Issue by mahmut-gundogdu** [ng-turkey/ngx-validate#93]
When the form does not have form group, ValidationGroupDirective throws an error.
https://stackblitz.com/edit/angular-ivy-yarpzq?file=src/app/app.component.html

**Comment by marvhen** [comment]
When will this fix be included in a release?

**Comment by tunttunen** [comment]
Been waiting this fix eagerly ever since reporting, any news on why this is kept delayed?
